package com.flexath.currencyapp.ui.theme

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

data class Dimensions(
    val smallPadding0: Dp = 0.dp,
    val smallPadding1: Dp = 0.dp,
    val smallPadding2: Dp = 0.dp,
    val smallPadding3: Dp = 0.dp,
    val smallPadding4: Dp = 0.dp,
    val smallPadding4_1: Dp = 0.dp,
    val smallPadding5: Dp = 0.dp,

    val mediumPadding1: Dp = 0.dp,
    val mediumPadding2: Dp = 0.dp,
    val mediumPadding3: Dp = 0.dp,
    val mediumPadding4: Dp = 0.dp,
    val mediumPadding5: Dp = 0.dp,

    val largePadding1: Dp = 0.dp,
    val largePadding2: Dp = 0.dp,
    val largePadding3: Dp = 0.dp,
    val largePadding4: Dp = 0.dp,
    val largePadding5: Dp = 0.dp,
    val largePadding6: Dp = 0.dp,
    val largePadding7: Dp = 0.dp,
    val largePadding8: Dp = 0.dp,
    val largePadding9: Dp = 0.dp,
    val largePadding10: Dp = 0.dp,

    val extraLargePadding1: Dp = 0.dp,
    val extraLargePadding2: Dp = 0.dp,
    val extraLargePadding3: Dp = 0.dp,
    val extraLargePadding4: Dp = 0.dp,
    val extraLargePadding5: Dp = 0.dp,
    val extraLargePadding6: Dp = 0.dp,
    val extraLargePadding7: Dp = 0.dp,
    val extraLargePadding8: Dp = 0.dp,
    val extraLargePadding9: Dp = 0.dp,
    val extraLargePadding10: Dp = 0.dp,

    val doubleExtraLargePadding1: Dp = 0.dp,
    val doubleExtraLargePadding2: Dp = 0.dp,
    val doubleExtraLargePadding3: Dp = 0.dp,
    val doubleExtraLargePadding4: Dp = 0.dp,
    val doubleExtraLargePadding5: Dp = 0.dp,
    val doubleExtraLargePadding6: Dp = 0.dp,
    val doubleExtraLargePadding7: Dp = 0.dp,
    val doubleExtraLargePadding8: Dp = 0.dp,
    val doubleExtraLargePadding9: Dp = 0.dp,
    val doubleExtraLargePadding10: Dp = 0.dp,

    val doubleExtraLargePadding2_wx: Dp = 0.dp,
    val extraLargePadding5_2x: Dp = 0.dp,
    val extraLargePadding10_2x: Dp = 0.dp,

    val productCardWidth: Dp = 0.dp,
    val articleCardWidth: Dp = 0.dp,
    val sellerProfileWidth: Dp = 0.dp,
    val categoryTextWidth: Dp = 0.dp,

    val smallText1: TextUnit = 0.sp,
    val smallText2: TextUnit = 0.sp,
    val smallText3: TextUnit = 0.sp,
    val smallText4: TextUnit = 0.sp,
    val smallText5: TextUnit = 0.sp,

    val mediumText1: TextUnit = 0.sp,
    val mediumText1_n: TextUnit = 0.sp,
    val mediumText2: TextUnit = 0.sp,
    val mediumText2_n: TextUnit = 0.sp,
    val mediumText3: TextUnit = 0.sp,
    val mediumText4: TextUnit = 0.sp,
    val mediumText5: TextUnit = 0.sp,

    val largeText1: TextUnit = 0.sp,
    val largeText2: TextUnit = 0.sp,
    val largeText3: TextUnit = 0.sp,
    val largeText4: TextUnit = 0.sp,
    val largeText5: TextUnit = 0.sp,
    val largeText6: TextUnit = 0.sp,
    val largeText7: TextUnit = 0.sp,
    val largeText8: TextUnit = 0.sp,
    val largeText9: TextUnit = 0.sp,
    val largeText10: TextUnit = 0.sp,

    val extraLargeText1: TextUnit = 0.sp,
    val extraLargeText2: TextUnit = 0.sp,
    val extraLargeText3: TextUnit = 0.sp,
    val extraLargeText4: TextUnit = 0.sp,
    val extraLargeText5: TextUnit = 0.sp,
    val extraLargeText6: TextUnit = 0.sp,
    val extraLargeText7: TextUnit = 0.sp,
    val extraLargeText8: TextUnit = 0.sp,
    val extraLargeText9: TextUnit = 0.sp,
    val extraLargeText10: TextUnit = 0.sp,
    val extraLargeText11: TextUnit = 0.sp,
    val extraLargeText12: TextUnit = 0.sp,
    val extraLargeText13: TextUnit = 0.sp,
    val extraLargeText14: TextUnit = 0.sp,
    val extraLargeText15: TextUnit = 0.sp,
    val extraLargeText16: TextUnit = 0.sp,
    val extraLargeText17: TextUnit = 0.sp,
    val extraLargeText18: TextUnit = 0.sp,
    val extraLargeText19: TextUnit = 0.sp,
    val extraLargeText20: TextUnit = 0.sp
)

val mediumCompatDimensions = Dimensions(
    smallPadding0 = 1.dp,
    smallPadding1 = 2.dp,
    smallPadding2 = 4.dp,
    smallPadding3 = 6.dp,
    smallPadding4 = 8.dp,
    smallPadding4_1 = 9.dp,
    smallPadding5 = 10.dp,

    mediumPadding1 = 12.dp,
    mediumPadding2 = 14.dp,
    mediumPadding3 = 16.dp,
    mediumPadding4 = 18.dp,
    mediumPadding5 = 20.dp,

    largePadding1 = 22.dp,
    largePadding2 = 24.dp,
    largePadding3 = 26.dp,
    largePadding4 = 28.dp,
    largePadding5 = 30.dp,
    largePadding6 = 32.dp,
    largePadding7 = 34.dp,
    largePadding8 = 36.dp,
    largePadding9 = 38.dp,
    largePadding10 = 40.dp,

    extraLargePadding1 = 42.dp,
    extraLargePadding2 = 44.dp,
    extraLargePadding3 = 46.dp,
    extraLargePadding4 = 48.dp,
    extraLargePadding5 = 50.dp,
    extraLargePadding6 = 52.dp,
    extraLargePadding7 = 54.dp,
    extraLargePadding8 = 56.dp,
    extraLargePadding9 = 58.dp,
    extraLargePadding10 = 60.dp,

    doubleExtraLargePadding1 = 62.dp,
    doubleExtraLargePadding2 = 64.dp,
    doubleExtraLargePadding3 = 66.dp,
    doubleExtraLargePadding4 = 68.dp,
    doubleExtraLargePadding5 = 70.dp,
    doubleExtraLargePadding6 = 72.dp,
    doubleExtraLargePadding7 = 74.dp,
    doubleExtraLargePadding8 = 76.dp,
    doubleExtraLargePadding9 = 78.dp,
    doubleExtraLargePadding10 = 80.dp,

    doubleExtraLargePadding2_wx = 64.dp,
    extraLargePadding5_2x = 100.dp,
    extraLargePadding10_2x = 120.dp,

    productCardWidth = 160.dp,
    articleCardWidth = 156.dp,
    sellerProfileWidth = 40.dp,
    categoryTextWidth = 60.dp,

    // Text
    smallText1 = 2.sp,
    smallText2 = 4.sp,
    smallText3 = 6.sp,
    smallText4 = 8.sp,
    smallText5 = 10.sp,

    mediumText1 = 12.sp,
    mediumText1_n = 13.sp,
    mediumText2 = 14.sp,
    mediumText2_n = 15.sp,
    mediumText3 = 16.sp,
    mediumText4 = 18.sp,
    mediumText5 = 20.sp,

    largeText1 = 22.sp,
    largeText2 = 24.sp,
    largeText3 = 26.sp,
    largeText4 = 28.sp,
    largeText5 = 30.sp,
    largeText6 = 32.sp,
    largeText7 = 34.sp,
    largeText8 = 36.sp,
    largeText9 = 38.sp,
    largeText10 = 40.sp,

    extraLargeText1 = 42.sp,
    extraLargeText2 = 44.sp,
    extraLargeText3 = 46.sp,
    extraLargeText4 = 48.sp,
    extraLargeText5 = 50.sp,
    extraLargeText6 = 52.sp,
    extraLargeText7 = 54.sp,
    extraLargeText8 = 56.sp,
    extraLargeText9 = 58.sp,
    extraLargeText10 = 60.sp,
    extraLargeText11 = 62.sp,
    extraLargeText12 = 64.sp,
    extraLargeText13 = 66.sp,
    extraLargeText14 = 68.sp,
    extraLargeText15 = 70.sp,
    extraLargeText16 = 72.sp,
    extraLargeText17 = 74.sp,
    extraLargeText18 = 76.sp,
    extraLargeText19 = 78.sp,
    extraLargeText20 = 80.sp
)

val smallCompatDimensions = Dimensions(
    smallPadding0 = 0.8.dp,
    smallPadding1 = 1.6.dp,
    smallPadding2 = 3.2.dp,
    smallPadding3 = 4.8.dp,
    smallPadding4 = 6.4.dp,
    smallPadding4_1 = 7.2.dp,
    smallPadding5 = 8.dp,

    mediumPadding1 = 9.6.dp,
    mediumPadding2 = 11.2.dp,
    mediumPadding3 = 12.8.dp,
    mediumPadding4 = 14.4.dp,
    mediumPadding5 = 16.dp,

    largePadding1 = 17.6.dp,
    largePadding2 = 19.2.dp,
    largePadding3 = 20.8.dp,
    largePadding4 = 22.4.dp,
    largePadding5 = 24.dp,
    largePadding6 = 25.6.dp,
    largePadding7 = 27.2.dp,
    largePadding8 = 28.8.dp,
    largePadding9 = 30.4.dp,
    largePadding10 = 32.dp,

    extraLargePadding1 = 33.6.dp,
    extraLargePadding2 = 35.2.dp,
    extraLargePadding3 = 36.8.dp,
    extraLargePadding4 = 38.4.dp,
    extraLargePadding5 = 40.dp,
    extraLargePadding6 = 41.6.dp,
    extraLargePadding7 = 43.2.dp,
    extraLargePadding8 = 44.8.dp,
    extraLargePadding9 = 46.4.dp,
    extraLargePadding10 = 48.dp,

    doubleExtraLargePadding1 = 49.6.dp,
    doubleExtraLargePadding2 = 51.2.dp,
    doubleExtraLargePadding3 = 52.8.dp,
    doubleExtraLargePadding4 = 54.4.dp,
    doubleExtraLargePadding5 = 56.dp,
    doubleExtraLargePadding6 = 57.6.dp,
    doubleExtraLargePadding7 = 59.2.dp,
    doubleExtraLargePadding8 = 60.8.dp,
    doubleExtraLargePadding9 = 62.4.dp,
    doubleExtraLargePadding10 = 64.dp,

    doubleExtraLargePadding2_wx = 51.2.dp,
    extraLargePadding5_2x = 80.dp,
    extraLargePadding10_2x = 96.dp,

    productCardWidth = 128.dp,
    articleCardWidth = 124.8.dp,
    sellerProfileWidth = 32.dp,
    categoryTextWidth = 48.dp,

    // Text
    smallText1 = 1.sp,
    smallText2 = 2.sp,
    smallText3 = 3.sp,
    smallText4 = 4.sp,
    smallText5 = 5.sp,

    mediumText1 = 6.sp,
    mediumText1_n = 6.5.sp,
    mediumText2 = 7.sp,
    mediumText3 = 8.sp,
    mediumText4 = 9.sp,
    mediumText5 = 10.sp,

    largeText1 = 11.sp,
    largeText2 = 12.sp,
    largeText3 = 13.sp,
    largeText4 = 14.sp,
    largeText5 = 15.sp,
    largeText6 = 16.sp,
    largeText7 = 17.sp,
    largeText8 = 18.sp,
    largeText9 = 19.sp,
    largeText10 = 20.sp,

    extraLargeText1 = 21.sp,
    extraLargeText2 = 22.sp,
    extraLargeText3 = 23.sp,
    extraLargeText4 = 24.sp,
    extraLargeText5 = 25.sp,
    extraLargeText6 = 26.sp,
    extraLargeText7 = 27.sp,
    extraLargeText8 = 28.sp,
    extraLargeText9 = 29.sp,
    extraLargeText10 = 30.sp,
    extraLargeText11 = 31.sp,
    extraLargeText12 = 32.sp,
    extraLargeText13 = 33.sp,
    extraLargeText14 = 34.sp,
    extraLargeText15 = 35.sp,
    extraLargeText16 = 36.sp,
    extraLargeText17 = 37.sp,
    extraLargeText18 = 38.sp,
    extraLargeText19 = 39.sp,
    extraLargeText20 = 40.sp
)

val largeCompatDimensions = Dimensions(
    smallPadding0 = 1.2.dp,
    smallPadding1 = 2.4.dp,
    smallPadding2 = 4.8.dp,
    smallPadding3 = 7.2.dp,
    smallPadding4 = 9.6.dp,
    smallPadding4_1 = 10.8.dp,
    smallPadding5 = 12.dp,

    mediumPadding1 = 14.4.dp,
    mediumPadding2 = 16.8.dp,
    mediumPadding3 = 19.2.dp,
    mediumPadding4 = 21.6.dp,
    mediumPadding5 = 24.dp,

    largePadding1 = 26.4.dp,
    largePadding2 = 28.8.dp,
    largePadding3 = 31.2.dp,
    largePadding4 = 33.6.dp,
    largePadding5 = 36.dp,
    largePadding6 = 38.4.dp,
    largePadding7 = 40.8.dp,
    largePadding8 = 43.2.dp,
    largePadding9 = 45.6.dp,
    largePadding10 = 48.dp,

    extraLargePadding1 = 50.4.dp,
    extraLargePadding2 = 52.8.dp,
    extraLargePadding3 = 55.2.dp,
    extraLargePadding4 = 57.6.dp,
    extraLargePadding5 = 60.dp,
    extraLargePadding6 = 62.4.dp,
    extraLargePadding7 = 64.8.dp,
    extraLargePadding8 = 67.2.dp,
    extraLargePadding9 = 69.6.dp,
    extraLargePadding10 = 72.dp,

    doubleExtraLargePadding1 = 74.4.dp,
    doubleExtraLargePadding2 = 76.8.dp,
    doubleExtraLargePadding3 = 79.2.dp,
    doubleExtraLargePadding4 = 81.6.dp,
    doubleExtraLargePadding5 = 84.dp,
    doubleExtraLargePadding6 = 86.4.dp,
    doubleExtraLargePadding7 = 88.8.dp,
    doubleExtraLargePadding8 = 91.2.dp,
    doubleExtraLargePadding9 = 93.6.dp,
    doubleExtraLargePadding10 = 96.dp,

    doubleExtraLargePadding2_wx = 76.8.dp,
    extraLargePadding5_2x = 120.dp,
    extraLargePadding10_2x = 144.dp,

    productCardWidth = 192.dp,
    articleCardWidth = 187.2.dp,
    sellerProfileWidth = 48.dp,
    categoryTextWidth = 72.dp,

    // Text
    smallText1 = 3.sp,
    smallText2 = 5.sp,
    smallText3 = 7.sp,
    smallText4 = 9.sp,
    smallText5 = 11.sp,

    mediumText1 = 13.sp,
    mediumText1_n = 14.sp,
    mediumText2 = 15.sp,
    mediumText3 = 17.sp,
    mediumText4 = 19.sp,
    mediumText5 = 21.sp,

    largeText1 = 23.sp,
    largeText2 = 25.sp,
    largeText3 = 27.sp,
    largeText4 = 29.sp,
    largeText5 = 31.sp,
    largeText6 = 33.sp,
    largeText7 = 35.sp,
    largeText8 = 37.sp,
    largeText9 = 39.sp,
    largeText10 = 41.sp,

    extraLargeText1 = 43.sp,
    extraLargeText2 = 45.sp,
    extraLargeText3 = 47.sp,
    extraLargeText4 = 49.sp,
    extraLargeText5 = 51.sp,
    extraLargeText6 = 53.sp,
    extraLargeText7 = 55.sp,
    extraLargeText8 = 57.sp,
    extraLargeText9 = 59.sp,
    extraLargeText10 = 61.sp,
    extraLargeText11 = 63.sp,
    extraLargeText12 = 65.sp,
    extraLargeText13 = 67.sp,
    extraLargeText14 = 69.sp,
    extraLargeText15 = 71.sp,
    extraLargeText16 = 73.sp,
    extraLargeText17 = 75.sp,
    extraLargeText18 = 77.sp,
    extraLargeText19 = 79.sp,
    extraLargeText20 = 81.sp
)